# Generated by Django 4.2.4 on 2024-01-17 16:05

import django.core.validators
from django.db import migrations, models
import main_app.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[main_app.custom_validators.letters_and_spaces_validator])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with a '+359' followed by 9 digits", regex='^\\+359[0-9]{9}$')])),
                ('website_url', models.URLField()),
            ],
        ),
    ]
