# Generated by Django 4.2.4 on 2024-01-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_foodcriticrestaurantreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menureview',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.menu'),
        ),
        migrations.AddIndex(
            model_name='menureview',
            index=models.Index(fields=['menu'], name='main_app_menu_review_menu_id'),
        ),
    ]
