# Generated by Django 4.2.4 on 2024-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_actor_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
