# Generated by Django 4.2.4 on 2023-12-19 21:29
import random

from django.db import migrations


def add_barcode(app, schema_editor):
    Product = app.get_model("main_app", "Product")
    products = Product.objects.all()
    all_barcodes = random.sample(range(100_000_000, 999_999_999), len(products))
    print(all_barcodes)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(add_barcode)
    ]
