# Generated by Django 4.2.4 on 2023-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand_name',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
