# Generated by Django 4.2.4 on 2023-12-20 20:25

from django.db import migrations


def set_price_based_on_brand(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone_model.objects.all()

    for phone in all_phones:
        phone.price = len(phone.brand) * 120

    smartphone_model.objects.bulk_update(all_phones, ['price'])


def reverse_set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default

    for phone in all_phones:
        phone.price = default_price

    smartphone_model.objects.bulk_update(all_phones, ['price'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_order_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_based_on_brand, reverse_set_price)
    ]
