# Generated by Django 4.2.4 on 2023-12-20 20:25

from django.db import migrations


def set_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone_model.objects.all()

    for phone in all_phones:
        phone.price = len(phone.brand) * 120
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'

    smartphone_model.objects.bulk_update(all_phones, ['price', 'category'])


def reverse_code(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default
    default_category = smartphone_model._meta.get_field('category').default

    for phone in all_phones:
        phone.price = default_price
        phone.category = default_category

    smartphone_model.objects.bulk_update(all_phones, ['price', 'category'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_order_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code)
    ]
