# Generated by Django 4.2.4 on 2023-12-20 21:38
from datetime import timedelta

from django.db import migrations


def delivery_warranty_mod(apps, schema_editor):
    order_model = apps.get_model("main_app", "Order")
    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == "Pending":
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()
        elif order.status == "Cancelled":
            order.delete()

    # order_model.objects.bulk_update(all_orders, ["delivery", "warranty"])

    print('Updated')


def reverse_delivery_warranty(apps, schema_editor):
    print("Reversed")


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_price_based_on_brand'),
    ]

    operations = [
        migrations.RunPython(delivery_warranty_mod, reverse_delivery_warranty)
    ]
