# Generated by Django 4.2.4 on 2024-08-03 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('manufacturer', models.CharField(max_length=100)),
                ('capacity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('launch_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Planned', max_length=9)),
                ('launch_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('astronauts', models.ManyToManyField(related_name='astronauts', to='main_app.astronaut')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commander', to='main_app.astronaut')),
                ('spacecraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='main_app.spacecraft')),
            ],
        ),
    ]
