# Generated by Django 4.2.4 on 2024-08-03 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spacecraft_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='spacewalks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
