# Generated by Django 4.2.4 on 2024-08-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_astronaut_spacewalks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronaut',
            old_name='deta_of_birth',
            new_name='date_of_birth',
        ),
    ]
