# Generated by Django 4.2.4 on 2024-01-29 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_videogame_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='The rating must be between 0.0 and 10.0'), django.core.validators.MaxValueValidator(limit_value=10.0, message='The rating must be between 0.0 and 10.0')]),
        ),
    ]
